# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MultiSelectionTable-Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'MultiSelectionTableView', :path => '../'
  pod 'SDWebImage', '~> 3.8.1'

  # Pods for MultiSelectionTable

  target 'MultiSelectionTable-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MultiSelectionTable-ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
